---
- name: Deploy carbide servers
  hosts: carbide_servers
  become: true
  roles:
    - carbide_server

- name: Deploy carbide sensors
  hosts: carbide_sensors
  become: true
  roles:
    - carbide_sensor
