FROM docker.io/library/alpine:3.21

RUN apk add --no-cache openssh-server openssh-client shadow curl \
 && mkdir -p /run/sshd /home/honey/.ssh \
 && adduser -D -s /bin/sh honey \
 && chown honey:honey /home/honey/.ssh \
 && chmod 700 /home/honey/.ssh \
 && echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config \
 && echo "PermitRootLogin no" >> /etc/ssh/sshd_config \
 && echo "Welcome to Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-91-generic x86_64)" > /etc/motd \
 && printf '# .profile\numask 022\n' > /home/honey/.profile \
 && chown honey:honey /home/honey/.profile

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]
